### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by gregdenay**
Preparing for release 1.0.0

TODO: 
- [x] changelog
- [x] version
- [x] solve merge confilicts (likely justs quash old files)

### CODE REVIEW

**Comment by gregdenay** [comment]
@marchoeppner I made the PR, which means you need to review it :)

**Review by marchoeppner — APPROVED** [review]
looks fine

**Comment by gregdenay** [comment]
merge and release?

**Comment by marchoeppner** [comment]
> merge and release?

Go for it!

**Comment by marchoeppner** [comment]
Actually, if you want to do the 1.0 release, the version in nextflow.config would have to be adjusted. I'll do that real quick..

**Comment by gregdenay** [comment]
Good job! :sparkles:

**Pull request merged**
