### PR TITLE
patch 1.0.0.alpha.1

### PR DESCRIPTION
**Pull request by gregdenay**
lint
fixes
set up branch protection and gh action

### CODE REVIEW

**Comment by marchoeppner** [comment]
Probably best to take the most recent dev branch to include the proper version from the manifest?

**Comment by marchoeppner** [comment]
I think you'll have to modify run_pipeline.yml to adjust the resource limits. For the generic test, we are doing this in conf/test.config. You could either add a new profile there (and reference it in nextflow.config) or adjust the linting process to include:

--max_cpus 4 --max_memory 12.GB 

Just so it doesn't blow up the small workflow runner that github provides.

**Comment by gregdenay** [comment]
CD-CI is running on main branch by defualt, so this is the old version. The new version on the dev branch is passing.
We'll need to bypass the requirements this time

**Comment by gregdenay** [comment]
If there are no other pending changes I would merge the PR and release a `alpha.1` or maybe `beta` version?

**Comment by marchoeppner** [comment]
@gregdenay  I just pushed some updates to the docs, but only minor stuff - so not critical for the alpha release

I think since this is the first attempt at a release version, alpha seems appropriate.

**Comment by marchoeppner** [comment]
It seems that the PR isn't seeing the latest version of the pipeline test? hm

**Pull request merged**
